### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by snunez1** [jolby/cl-tokenizers#3]
A few questions:

- Are there long-term plans for log4cl?  It seems to be used in only one place, and it might be better to raise a `cerror` at that location instead so a recovery is possible, if desired.
- `serapeum` is a dependency, but not used anywhere.  It's a _huge_ dependency too, so if it's not being used, it's probably better to avoid it.  I usually avoid it anyway.
- The ASDF file has the following at the start of the file:
```
(in-package :cl-user)
(defpackage tokenizers-asd
  (:use :cl :asdf))
(in-package :tokenizers-asd)
```
Normally all of this would not be neccessary.  Is there something going on that's not obvious to me?

Finally, if you're open to pull requests, I can submit them as and when I clean up bits and bobs like this.

**Comment by jolby** [comment]
I've cleaned up the asdf system file, removing some dependencies (log4cl, serapeum). They were useful for debugging as I was scribbling around when first developing this. I've moved the cli interface into its own system and the clingon dep along with it. We could also part out the dexador dep by moving the downloader into its own system that people would only need to use once.

I'm open to pull requests, but I will be traveling the next few weeks so responses might be delayed. 

The unit tests have 1 known failure due to not correctly encoding/detecting some unicode  wide chars. I'll make an issue.
