### ISSUE TITLE
README example not working

### ISSUE THREAD

**Issue by snunez1** [jolby/cl-tokenizers#4]
`CL-USER> (defparameter *cl100k-encoder* (tokenizers:get-encoder :tiktokken "cl100k_base"))`

leads to:

```
There is no applicable method for the generic function:
  #<STANDARD-GENERIC-FUNCTION TOKENIZERS:GET-ENCODER #x2103E592EF>
when called with arguments:
  (:TIKTOKKEN "cl100k_base")
   [Condition of type NO-APPLICABLE-METHOD-EXISTS]
```

which appears to be caused at [line 141](https://github.com/jolby/cl-tokenizers/blob/efc39150a29fee4906c50c7807dece1881655fe2/src/tiktoken.lisp#L141) in tiktoken.lisp where 2 arguments are expected, but only one received.  Is this a possibly circular call? 

Separately, is there a reason (other than convenience at this point), for `eql` specialisation of `get-encoder`?

**Comment by jolby** [comment]
README example should be working now (it was due to the reference to the 'kk' in the tiktokken). The faulty call on 141 should be fixed as well.

The eql specializations are because I'd like to enable (for myself and others) the ability to have different configurations of sets of encoders using simple designators as the lookup keys.
